### PR TITLE
New script for fixtures

### LINKED ISSUE #3: [BUG] Serialize the same proving key for both compressed and uncompressed
Instead of creating separate pk/vk pairs: https://github.com/webb-tools/protocol-substrate-fixtures/blob/main/builder/src/main.rs#L24-L25 we should use one pair

### PR DESCRIPTION
**Pull request by lazovicff**

### CODE REVIEW

**Comment by lazovicff** [comment]
On current branch/`709d2ca`:

added QmcC5SCHKi74azZUqR4RNqJ3FKGntFNQMqEB8a2kmAmrBr mixer/bn254/x5/proving_key.bin
added QmYDtGX7Wf5qUPEpGsgrX6oss2m2mm8vi7uzNdK4C9yJdZ mixer/bn254/x5/proving_key_uncompressed.bin
added QmUfSNRVBLVYdThWPyw44rGpnLiMAGfaWKQ2wKgr9KqWVx mixer/bn254/x5/verifying_key.bin
added Qmck3VEL6bufTE9vJPvup42NyYcik2nr8y5sxYzYY6Y3XF mixer/bn254/x5/verifying_key_uncompressed.bin
added QmV5ajfQucw2QuP6LeaeFC6GJQ8gb7WGr1aU41H1sta1kA mixer/bn254/x5
added QmeosroD7UnXxqepjocpKGv2R3gQNLCsqdZLcXVSo1rYi7 mixer/bn254
added QmePs7XmtPw3sFVNND6aUeDBiqxf2rxqi4swUQ68ggj3bd mixer

**Comment by lazovicff** [comment]
On `main`/`a4f433a`:

added QmXnmehFYKTMEPaoK6AYZcNsFZPxZ44N47P3Em6LimSkA8 mixer/bn254/x5/proving_key.bin
added QmRPEXC5umwfNnBM2yFkcyatedoDNhwTLx2NLV8JNayQnM mixer/bn254/x5/proving_key_uncompressed.bin
added QmaavLcxLNDzxxTjsCJWes6XazdwtX9J5BKhuScB9Lg6Yi mixer/bn254/x5/verifying_key.bin
added QmPtgrAmig4aExx7JcHagCEP3YrAXCcEAxsY4C4Bp4bXh3 mixer/bn254/x5/verifying_key_uncompressed.bin
added QmeLm4onCBvhL35gWipc1zpHWs2ctbQdVJBsgRH27tqgpE mixer/bn254/x5
added QmUhafuEewX6vPtrxfSLxwZKZyrRCtC48ZrrjJHTptA3ZU mixer/bn254
added QmUteUT9q6RzEXr9pc8446tXSR6ZjZnAiX5Tv3tYt2owzB mixer

**Comment by lazovicff** [comment]
On `main`/`d4df01f`

added QmXnmehFYKTMEPaoK6AYZcNsFZPxZ44N47P3Em6LimSkA8 mixer/bn254/x5/proving_key.bin
added QmQWnELR1oRUpoAo6URNK2XbGCfEk6sPdJioeSYqZW6cqi mixer/bn254/x5/proving_key_uncompresed.bin
added QmaavLcxLNDzxxTjsCJWes6XazdwtX9J5BKhuScB9Lg6Yi mixer/bn254/x5/verifying_key.bin
added QmS4uz1s4pQ1NZCbBEttq4wZZ8vjH7w5KgBhfJkatAFCeF mixer/bn254/x5
added QmVbudWWbwChb63empkYWHEVs5qLCAcaR1B2KGienUgynV mixer/bn254
added QmbQssLY7WwvSxBer9HJrNT7r6ULRKR1c9kKEBf6z7BKWD mixer

**Comment by lazovicff** [comment]
Not sure why these differ. Namely, the first and the third one

**Comment by nepoche** [comment]
Attempting an integration test with these repos:
- Webb-dapp: [0375d62c97](https://github.com/webb-tools/webb-dapp/commit/0375d62c974c5cd25f2667deeffbbd5e8f7690ad)
- Protocol-substrate: [e07b3f59](https://github.com/webb-tools/protocol-substrate/tree/e07b3f59f96c5099810b5dd5ed21647a76327771)
- Protocol-substrate-fixtures: This PR.

I get a `mixerBn254.InvalidWithdrawProof` error.

On protocol-substrate-fixtures: d4df01f, there is no such error.

**Comment by lazovicff** [comment]
Try using last commit from this PR: https://github.com/webb-tools/protocol-substrate/pull/101, so `a57e968`

**Comment by nepoche** [comment]
I encounter the same issue on protocol-substrate a57e968

**Comment by lazovicff** [comment]
Then I'm not sure. I will help debug it next week

**Review by AhmedKorim — APPROVED** [review]
LGTM tested with webb.js `4-26` ,dApp https://github.com/webb-tools/webb-dapp/tree/7a4436023c879a764a31bb9d6b6d9b388db1d119 , and node https://github.com/webb-tools/protocol-substrate/pull/101/commits/8e8d0c7a4ca87581a5ff1984661dbe9077d849c3

**Pull request merged**
